# Generated by Django 2.0 on 2018-12-30 20:34

from django.db import migrations, models
import django.db.models.deletion
import school_management_app.constants.model_constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(school_management_app.constants.model_constants.AttendanceStatus('P'), 'P'), (
                school_management_app.constants.model_constants.AttendanceStatus('A'), 'A')], max_length=2)),
            ],
        ),

        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(school_management_app.constants.model_constants.ExamStatus('ACTIVE'), 'ACTIVE'), (
                school_management_app.constants.model_constants.ExamStatus('EXPIRED'), 'EXPIRED')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamMarksRecords',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.ExamHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[(school_management_app.constants.model_constants.UserType('PARENT'), 'PARENT'), (
                school_management_app.constants.model_constants.UserType('TEACHER'), 'TEACHER'), (
                                                   school_management_app.constants.model_constants.UserType('STUDENT'), 'STUDENT')], max_length=4)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjectEngagment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='studentexammarksrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User'),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User'),
        ),
    ]
