# Generated by Django 2.0 on 2019-01-02 20:00

from django.db import migrations, models
import django.db.models.deletion
import school_management_app.constants.model_constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(school_management_app.constants.model_constants.AttendanceStatus('P'), 'P'), (school_management_app.constants.model_constants.AttendanceStatus('A'), 'A')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[(school_management_app.constants.model_constants.ExamStatus('ACTIVE'), 'ACTIVE'), (school_management_app.constants.model_constants.ExamStatus('EXPIRED'), 'EXPIRED')], max_length=2)),
                ('marks_entered', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamRecords',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('marks', models.IntegerField(default=-1)),
                ('outof', models.IntegerField(default=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.ExamHistory')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[(school_management_app.constants.model_constants.UserType('PARENT'), 'PARENT'), (school_management_app.constants.model_constants.UserType('TEACHER'), 'TEACHER'), (school_management_app.constants.model_constants.UserType('STUDENT'), 'STUDENT')], max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('enrolled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjectEngagment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='studentexamrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User'),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management_app.User'),
        ),
    ]
