# Generated by Django 2.0 on 2019-01-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0002_auto_20190102_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examhistory',
            name='user',
        ),
    ]
