# Generated by Django 2.0 on 2019-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0003_remove_examhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexammarksrecords',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='studentexammarksrecords',
            name='outof',
            field=models.IntegerField(default=100),
        ),
    ]
