# Generated by Django 2.0 on 2019-01-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0003_auto_20190101_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_management_app.Subjects'),
        ),
    ]
