# Generated by Django 2.0 on 2019-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0004_attendance_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
