# Generated by Django 2.0 on 2019-01-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0005_user_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
