# Generated by Django 2.0 on 2019-01-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0005_auto_20190102_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='examhistory',
            name='marks_entered',
            field=models.BooleanField(default=0),
        ),
    ]
